<a href="https://colab.research.google.com/github/Gabriel-Kelvin184/Python/blob/main/Lab_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Write a program to distinguish between Array Indexing and Fancy Indexing.


In [ ]:
import numpy as np

def is_array_indexing(array, index):

  if len(index) != array.ndim:
    return False

  for i, idx in enumerate(index):
    if not isinstance(idx, int):
      return False

    if idx < 0 or idx >= array.shape[i]:
      return False
  return True

def is_fancy_indexing(array, index):
  return not is_array_indexing(array, index)

array = np.array([[1, 2, 3], [4, 5, 6]])

index = (0, 1)
print(is_array_indexing(array, index))

index = (0, [0, 2])
print(is_fancy_indexing(array, index))

True
True


2. Execute the 2D array Slicing.

In [ ]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sliced_array = array[:2]

print(sliced_array)

[[1 2 3]
 [4 5 6]]


3. Create the 5-Dimensional arrays using ‘ndmin’.

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

five_d_array = np.array(array, ndmin=5)

print(five_d_array)

[[[[[1 2 3 4 5]]]]]


4. Reshape the array from 1-D to 2-D array.

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

reshaped_array = array.reshape((3, 3))

print(reshaped_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


5. Perform the Stack functions in Numpy arrays – Stack(), hstack(), vstack(), and dstack().

In [ ]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

stacked_array = np.stack([array1, array2])

hstacked_array = np.hstack([array1, array2])

vstacked_array = np.vstack([array1, array2])

dstacked_array = np.dstack([array1, array2])

print(stacked_array)
print(hstacked_array)
print(vstacked_array)
print(dstacked_array)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


6. Perform the searchsort method in Numpy array.

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
value = 6

index = np.searchsorted(array, value)

print(f"The index where the value {value} would be inserted is {index}")

The index where the value 6 would be inserted is 5


7. Create Numpy Structured array using your domain features.

In [ ]:
import numpy as np

features = ["stock", "price"]
dtype = np.dtype([('stock', 'U10'), ('price', 'i4')])

array = np.array([
    ('Tesla', 22),
    ('Wipro', 25),
    ('Infosys', 23)
], dtype=dtype)

print(array)


[('Tesla', 22) ('Wipro', 25) ('Infosys', 23)]


8. Create Data frame using List and Dictionary.


In [ ]:
import pandas as pd

student_records = [
    {
        "name": "Luffy",
        "age": 21,
        "gpa": 3.5
    },
    {
        "name": "Zoro",
        "age": 25,
        "gpa": 3.75
    },
    {
        "name": "Sanji",
        "age": 22,
        "gpa": 3.25
    }
]

df = pd.DataFrame(student_records)
print(df)


    name  age   gpa
0  Alice   25  3.50
1    Bob   30  3.75
2  Carol   28  3.25


9. Create Data frame on your Domain area and perform the following operations to find and eliminate the
missing data from the dataset.
• isnull()
• notnull()
• dropna()
• fillna()
• replace()
• interpolate()

In [ ]:
import pandas as pd

# Create a list of dictionaries
domain_records = [
    {
        "feature1": "value1",
        "feature2": 20,
        "feature3": 30.5
    },
    {
        "feature1": "value2",
        "feature2": None,
        "feature3": 40
    },
    {
        "feature1": "value3",
        "feature2": 50,
        "feature3": None
    }
]

# Create a DataFrame from the list of dictionaries
df = pd.DataFrame(domain_records)

# Find missing values
missing_values = df.isnull().sum()

# Eliminate missing values
if missing_values.sum() > 0:
    # Drop rows with missing values
    df = df.dropna()

    # Fill in missing values with mean
    df = df.fillna(method="mean")

    # Replace "None" with 0
    df = df.replace("None", 0)

    # Interpolate missing values
    df = df.interpolate()

print(df)


10. Perform the Hierarchical Indexing in the above created dataset.

In [ ]:
import pandas as pd

# Create a list of dictionaries
domain_records = [
    {
        "feature1": "value1",
        "feature2": 20,
        "feature3": 30.5
    },
    {
        "feature1": "value2",
        "feature2": None,
        "feature3": 40
    },
    {
        "feature1": "value3",
        "feature2": 50,
        "feature3": None
    }
]

# Create a DataFrame from the list of dictionaries
df = pd.DataFrame(domain_records)

# Perform hierarchical indexing
df = df.set_index(["feature1", "feature2"])

# Print the DataFrame
print(df)


                   feature3
feature1 feature2          
value1   20.0          30.5
value2   NaN           40.0
value3   50.0           NaN
