<a href="https://colab.research.google.com/github/Gabriel-Kelvin184/Python/blob/main/Lab_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1. Create two 3×3 matrices using the random function in Numpy and perform the following operations.
Product (prod)
Multiplication (multiply)
Dot Product (dot)

In [6]:
import numpy as np

A = np.random.randint(0, 10, size=(3, 3))
B = np.random.randint(0, 10, size=(3, 3))

print('Matrix A:')
print(A)
print('Matrix B:')
print(B)

product = np.prod(A * B)
print('Product of matrices A and B:')
print(product)

multiplication = A * B
print('Multiplication of matrices A and B:')
print(multiplication)

dot_product = np.dot(A, B)
print('Dot product of matrices A and B:')
print(dot_product)


Matrix A:
[[9 5 2]
 [9 7 3]
 [3 4 0]]
Matrix B:
[[0 3 3]
 [6 4 6]
 [2 7 4]]
Product of matrices A and B:
0
Multiplication of matrices A and B:
[[ 0 15  6]
 [54 28 18]
 [ 6 28  0]]
Dot product of matrices A and B:
[[34 61 65]
 [48 76 81]
 [24 25 33]]


Q2. Perform the following set operations using the Numpy functions.
Union
Intersection
Set difference
XOR

In [2]:
import numpy as np

set_a = np.array([1, 2, 3, 4, 5])
set_b = np.array([3, 4, 5, 6, 7])

union = np.union1d(set_a, set_b)
print('Union of set_a and set_b:')
print(union)

intersection = np.intersect1d(set_a, set_b)
print('Intersection of set_a and set_b:')
print(intersection)

difference = np.setdiff1d(set_a, set_b)
print('Difference of set_a and set_b:')
print(difference)

xor = np.setxor1d(set_a, set_b)
print('XOR of set_a and set_b:')
print(xor)

Union of set_a and set_b:
[1 2 3 4 5 6 7]
Intersection of set_a and set_b:
[3 4 5]
Difference of set_a and set_b:
[1 2]
XOR of set_a and set_b:
[1 2 6 7]


Q3. Create a 1D array using Random function and perform the following operations.
Cumulative sum
Cumulative Product
Discrete difference (with n=3)
Find the unique elements from the array

In [8]:
import random

array = [random.randint(1, 100) for i in range(10)]
print("Original array:")
print(array)

cumulative_sum = []
for i in range(len(array)):
    if i == 0:
        cumulative_sum.append(array[i])
    else:
        cumulative_sum.append(cumulative_sum[i - 1] + array[i])

print("Cumulative sum of the array:")
print(cumulative_sum)

cumulative_product = []
for i in range(len(array)):
    if i == 0:
        cumulative_product.append(array[i])
    else:
        cumulative_product.append(cumulative_product[i - 1] * array[i])

print("Cumulative product of the array:")
print(cumulative_product)

discrete_difference = []
for i in range(len(array) - 2):
    discrete_difference.append(array[i + 2] - array[i])

print("Discrete difference of the array (n=3):")
print(discrete_difference)

unique_elements = set(array)
print("Unique elements from the array:")
print(unique_elements)

Original array:
[78, 33, 50, 37, 82, 93, 24, 36, 44, 90]
Cumulative sum of the array:
[78, 111, 161, 198, 280, 373, 397, 433, 477, 567]
Cumulative product of the array:
[78, 2574, 128700, 4761900, 390475800, 36314249400, 871541985600, 31375511481600, 1380522505190400, 124247025467136000]
Discrete difference of the array (n=3):
[-28, 4, 32, 56, -58, -57, 20, 54]
Unique elements from the array:
{33, 36, 37, 44, 78, 50, 82, 24, 90, 93}


Q4. Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())

In [10]:
import numpy as np

array_1 = np.array([1, 2, 3, 4, 5])
array_2 = np.array([6, 7, 8, 9, 10])

addition_1 = []
for i, j in zip(array_1, array_2):
    addition_1.append(i + j)

print("Addition using zip() and add():")
print(addition_1)

def add_function(x, y):
    return x + y

addition_2 = np.vectorize(add_function)
addition_2 = addition_2(array_1, array_2)

print("Addition using user defined function:")
print(addition_2)


Addition using zip() and add():
[7, 9, 11, 13, 15]
Addition using user defined function:
[ 7  9 11 13 15]


Q5. Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce().

In [14]:
from functools import reduce

def gcd(x, y):
    while y:
        x, y = y, x % y
    return x

def lcm(x, y):
    return x * y // gcd(x, y)

array = [10, 20, 30]
lcm_array = reduce(lcm, array)
gcd_array = reduce(gcd, array)

print("The LCM of the array elements is:", lcm_array)
print("The GCD of the array elements is:", gcd_array)


The LCM of the array elements is: 60
The GCD of the array elements is: 10
